### ISSUE TITLE
Indenting issue after removing comments at smelt phase

### ISSUE THREAD

**Issue by woojae-siloai** [silogen/cluster-forge#51]
1. Create kube-prometheus-stack manifests:
`helm --namespace prometheus-system template prometheus prometheus-community/kube-prometheus-stack --create-namespace --version 48.2.1 -f overrides.yaml > manifests.yaml`

2. Search "prometheus-kube-prometheus-alertmanager.rules"

- Issue at line number 2256, "alert: AlertmanagerMembersInconsistent"  
- After removing comments by cluster-forge, smelting fails.
```
   - alert: AlertmanagerMembersInconsistent
     annotations:
       description: Alertmanager {{ $labels.namespace }}/{{ $labels.pod}} has only found {{ $value }} members of the {{$labels.job}} cluster.
       runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagermembersinconsistent
       summary: A member of an Alertmanager cluster has not found all other cluster members.
     expr: |-
       # Without max_over_time, failed scrapes could create false negatives, see
       # https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0 for details.
         max_over_time(alertmanager_cluster_members{job="prometheus-kube-prometheus-alertmanager",namespace="prometheus-system"}[5m])
       < on (namespace,service,cluster) group_left
         count by (namespace,service,cluster) (max_over_time(alertmanager_cluster_members{job="prometheus-kube-prometheus-alertmanager",namespace="prometheus-system"}[5m]))
     for: 15m
     labels:
       severity: critical
```

 - This works. Indentation modified manually at "max_over_time" and "count by"
```
   - alert: AlertmanagerMembersInconsistent
     annotations:
       description: Alertmanager {{ $labels.namespace }}/{{ $labels.pod}} has only found {{ $value }} members of the {{$labels.job}} cluster.
       runbook_url: https://runbooks.prometheus-operator.dev/runbooks/alertmanager/alertmanagermembersinconsistent
       summary: A member of an Alertmanager cluster has not found all other cluster members.
     expr: |-
       # Without max_over_time, failed scrapes could create false negatives, see
       # https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0 for details.
       max_over_time(alertmanager_cluster_members{job="prometheus-kube-prometheus-alertmanager",namespace="prometheus-system"}[5m])
       < on (namespace,service,cluster) group_left
       count by (namespace,service,cluster) (max_over_time(alertmanager_cluster_members{job="prometheus-kube-prometheus-alertmanager",namespace="prometheus-system"}[5m]))
     for: 15m
     labels:
       severity: critical
```
